### ISSUE TITLE
Releases 命名规范化小建议

### ISSUE THREAD

**Issue by CeeIM** [dogbutcat/gclone#15]
希望 Releases 文件名可以通过一些变量引用，方便写入到脚本中，也更加规范。

例如默认名称：`gclone-v1.61.0-mod1.5.1-linux-386.deb`
如果写成这样：`gclone-v1.61.0-mod1.5.1-Linux-x86_64.deb`

也许更好，可以很愉快的通过 `uname -s` or `uname -m` 来引用，参考原项目的 [Releases](https://github.com/donwa/gclone/releases)。
当然不止于此，只是一个例子，还有很多场景需要更规范的名称来简化额外工作。
感谢。

**Comment by dogbutcat** [comment]
Thank you for advising. I copied rclone Release naming.
