### ISSUE TITLE
Rclone v1.62.2 update

### ISSUE THREAD

**Issue by erdincsk** [dogbutcat/gclone#17]
Hello,

would it be possible to build gclone with rclone release v1.62.2?

thanks.

**Comment by dogbutcat** [comment]
I've seen the offical changelog, if minor verison bugfix not too sevious, normally I won't do that.

https://github.com/dogbutcat/gclone/releases/tag/v1.62.2-mod1.5.2 update is about my bugfix about change sa file. Upgrade  in your flavor.
