### ISSUE TITLE
What 403 Means ?

### ISSUE THREAD

**Issue by CyberPoison** [dogbutcat/gclone#18]
Hello i have setup everything (Created SA, Added to Group, added group to team drive) 
But when performing this command. 

```
gclone copy src100:/ dst100:/  --drive-server-side-across-configs --config ./gclone.conf --fast-list --progress -vv
```

my gclone version
```
root@ubuntu-4gb-nbg1-2:~/AutoRclone# gclone version rclone v1.62.0-DEV
- os/version: ubuntu 22.04 (64 bit)
- os/kernel: 5.15.0-67-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.18.1
- go/linking: dynamic
- go/tags: cmount
```

Ram: 8Gb
CPU: 4 Cores

When executing the command above i get tons of this error.

<img width="1097" alt="CleanShot 2023-03-26 at 04 59 15@2x" src="https://user-images.githubusercontent.com/60718477/227752821-afebc122-ea93-414d-8bde-98b0be5f4152.png">

my gclone config
```
[src100]
type = drive
scope = drive
service_account_file = /root/AutoRclone/accounts2/1.json
service_account_file_path = /root/AutoRclone/accounts2/
team_drive = xxxxxxxxx-xxxxxxxxx

[dst100]
type = drive
scope = drive
service_account_file = /root/AutoRclone/accounts2/1.json
service_account_file_path = /root/AutoRclone/accounts2/
team_drive = xxxxxxxx-xxxxxxxx
```
Is there any cap/limit on how much i can copy from both google shared drives, or on api limits ? 

Btw this is the API Errors.
<img width="1140" alt="CleanShot 2023-03-26 at 05 02 54@2x" src="https://user-images.githubusercontent.com/60718477/227752930-b13ede38-9c88-451f-a0d7-614f989f5a30.png">

if you need more info i will be here to provide more informations. 

Kind regards.

**Comment by CyberPoison** [comment]
Btw i can copy and download file from src directly over the web UI of google drive..

**Comment by dogbutcat** [comment]
From information you given, I guess you are backing up huge data between drives.

1. According the situation, you are not using my func in readme https://github.com/dogbutcat/gclone#4support-command-line-option---drive-rolling-sa-and---drive-rolling-count. So it will consume target sa file till the quote, 750GB about, then it goes finding the next usable one, like original gclone.

2. From your config, I see you setting two drives with shared sa path, while either one would use the consumed one which maybe already consumed 750 quote, as two drive could not share consumed sa file info. So it will appear 403 multiple times to changing.

3. All info written in readme is not all limit of drive api, as google also knew such action, variant error may occurring while copy or sync huge data with given rate limit. That’s why I come to add extra options to make the progress more sustainable.

I don’t know if you could understand what I talking about, but summery is your log is all normal. Thank you.

**Comment by dogbutcat** [comment]
While diving in the `Changing Service Account` log with same new sa file name, I've made a bugfix in 
 https://github.com/dogbutcat/gclone/releases/tag/v1.62.2-mod1.5.2.
 
 Upgrade in your flavor. Thanks for your support!
