### ISSUE TITLE
请问现在新增的参数是否还不支持环境变量模式

### ISSUE THREAD

**Issue by haig233** [dogbutcat/gclone#20]
https://rclone.org/docs/#environment-variables  环境变量模式相关介绍

环境变量相关设置：
![image](https://user-images.githubusercontent.com/25719719/235294113-711094c6-dafb-44ab-9676-dc04ca7e21be.png)

![image](https://user-images.githubusercontent.com/25719719/235294128-a75236e4-0e68-4c3e-ad33-06129802a7e1.png)

看见文件依然没有进行sa的轮换？

**Comment by dogbutcat** [comment]
Try use variables all in `_` like`RCLONE_DRIVE_ROLLING_COUNT`.

Parsing environment variables based on rclone's inner func, I'm not dealing extra opts.
