### ISSUE TITLE
--drive-rolling-sa only working with google to google transfer?

### ISSUE THREAD

**Issue by JoshBeer** [dogbutcat/gclone#21]
Hi,

could it be that the drive rolling only works when copying from one google shared drive to another google shared drive?
I'm currently migrating all my data from google to dropbox and I have been running the following command for it:

`gclone copy sd1:Media/TV dbx:Media/TV --drive-random-pick-sa --drive-rolling-sa --drive-rolling-count=6 --fast-list --max-backlog=2000000 --buffer-size=128M --dropbox-batch-size 70 --dropbox-batch-mode async --dropbox-batch-timeout 20s --tpslimit-burst=0 --tpslimit=10 --transfers=6 --use-mmap --no-update-modtime --dropbox-chunk-size=128M --progress -vP --max-transfer 18T --cutoff-mode=soft --bwlimit 110M`

My expectation would have been that after every 6 successful file transfers a new SA would be used for sd1.
But google admin console (Rporting -> Audit and investigation -> drive log events) clearly shows that gclone uses the same SA for the whole time.

Or did I understand the drive-rolling-sa command wrong?

Cheers!

**Comment by dogbutcat** [comment]
Sorry for late reply.

from your provide `But google admin console (Rporting -> Audit and investigation -> drive log events) `, I checked my log which mounted disk while dealing my file.
![image](https://github.com/dogbutcat/gclone/assets/8625449/da63c33d-4c6a-4498-8c59-01ce8b5210e5)

Seems no problem with it. In my opion, mounting is more similar with moving file between file providers.

Could you try with mounting opt or moving between drives?

**Comment by dogbutcat** [comment]
close for stale, feel free to open again if has any questions.
