### ISSUE TITLE
gclone selfupdate

### ISSUE THREAD

**Issue by JoseAngelB** [dogbutcat/gclone#24]
When using the command `gclone selfupdate` it updates to the last rclone official version instead the gclone mod

**Comment by dogbutcat** [comment]
OK got it. I've never heard that function. Thank you for advising.

**Comment by dogbutcat** [comment]
introduced `v1.64.0-mod1.6.0` coming with `gselfupdate` and `gversion`

`gclone gselfupdate [--check] [--output [of]] [--version [v]] [--package [zip|deb|rpm]]`
