### ISSUE TITLE
--drive-random-pick-sa not random

### ISSUE THREAD

**Issue by JoseAngelB** [dogbutcat/gclone#26]
It always uses the same SA accounts in the same order, it seems [the random always have the same seed](https://stackoverflow.com/questions/39529364/go-rand-intn-same-number-value)

**Comment by dogbutcat** [comment]
Sorry for late reply and thank you for providing help, add seed source in gclone v1.66.0-mod1.6.1

you can update through `gclone gselfupdate` when your local version is >=1.64.0-mod1.6.0
OR
download from [release](https://github.com/dogbutcat/gclone/releases) page

**Comment by JoseAngelB** [comment]
I don't know why but this stills happens

**Comment by dogbutcat** [comment]
@JoseAngelB I've made the rand-seed more random and add its unittest, seems working fine. If you can try `v1.67.0-mod1.6.2` or run `gclone gselfupdate` if your version is above `v1.64.0`
https://github.com/dogbutcat/gclone/blob/ee0c7e2fee3ad67c96b04d9abe323ad2b6a2a005/backend/drive/saInfo.go#L127-L130
