### ISSUE TITLE
userrate limit with sa

### ISSUE THREAD

**Issue by erdincsk** [dogbutcat/gclone#3]
Hello,

I'm getting userrate limit even i'm using more than 4-5 service accounts and can not copy more than 750gb.

Do you know there is an issue with google api or is it still possible to copy more than 750gb with multiple service accounts?

i'm just triying to copy files within the same account and shared drive.

thanks!

> 2021/11/16 16:44:30 Can't set -v and --log-level
2021/11/16 16:45:39 Can't set -v and --log-level
2021/11/16 16:46:08 DEBUG : rclone: Version "v1.57.0-DEV" starting with parameters ["./gclone" "copy" "edu-79:/test-1" "edu-79:/test-2" "--drive-server-side-across-configs" "--progress" "-vv" "--log-file=/Users/d23-2/log/log.log"]
2021/11/16 16:46:08 DEBUG : Creating backend with remote "edu-79:/test-1"
2021/11/16 16:46:08 DEBUG : Using config file from "/Users/user/.config/rclone/rclone.conf"
2021/11/16 16:46:08 DEBUG : edu-79: detected overridden config - adding "{Db_Y9}" suffix to name
2021/11/16 16:46:09 DEBUG : fs cache: renaming cache item "edu-79:/test-1" to be canonical "edu-79{Db_Y9}:test-1"
2021/11/16 16:46:09 DEBUG : Creating backend with remote "edu-79:/test-2"
2021/11/16 16:46:09 DEBUG : edu-79: detected overridden config - adding "{Db_Y9}" suffix to name
2021/11/16 16:46:09 DEBUG : fs cache: renaming cache item "edu-79:/test-2" to be canonical "edu-79{Db_Y9}:test-2"
2021/11/16 16:46:10 DEBUG : Google drive root 'test-2': Waiting for checks to finish
2021/11/16 16:46:10 DEBUG : Google drive root 'test-2': Waiting for transfers to finish
2021/11/16 16:46:10 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded)
2021/11/16 16:46:10 DEBUG : pacer: Rate limited, increasing sleep to 1.413914744s
2021/11/16 16:46:11 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded)
2021/11/16 16:46:11 DEBUG : pacer: Rate limited, increasing sleep to 2.993718685s
2021/11/16 16:46:11 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded)
2021/11/16 16:46:11 DEBUG : pacer: Rate limited, increasing sleep to 4.264291623s
2021/11/16 16:46:11 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded)
2021/11/16 16:46:11 DEBUG : pacer: Rate limited, increasing sleep to 8.065194508s
2021/11/16 16:46:11 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded)
2021/11/16 16:46:11 DEBUG : pacer: Rate limited, increasing sleep to 16.413468705s
2021/11/16 16:46:13 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded)
2021/11/16 16:46:13 DEBUG : pacer: Rate limited, increasing sleep to 16.141815546s

**Comment by dogbutcat** [comment]
I've use 2 days to test with latest gclone[1.57.0] without problem in switching sa for 3 times till comment still transfering.
![image](https://user-images.githubusercontent.com/8625449/143515788-84755626-cd1e-4e0c-853c-aa6834241be8.png)

> so the function has no problem :)

For the error you meet, I can share my experience below:

Does the shared file hit the google limit? As there is many hidden rules behind the file.
eg. 
* one file could not be downloading many time in certain hour(I used download one file in 50 thread, then boooom)
* also one file could not be downloaded over 5tb or it will be locked forever
* when the file marked abuse which you can see a little gray flag beside file name in web
* ...

All these error above will cause userRateLimitExceeded.

Could you try to download from web to check if file is really availiable?

**Comment by CyberPoison** [comment]
I also facing this issue, but i can download file and copy but not over api, i don't understand why 🤔
