### ISSUE TITLE
Doesn't work on Termux

### ISSUE THREAD

**Issue by l3v11** [dogbutcat/gclone#4]
![IMG_20211118_182436](https://user-images.githubusercontent.com/57452819/142414979-3e047602-7fb1-45a2-98aa-1ab7695c4640.jpg)

Doesn't work on Termux, tried all arch binaries. Shows this error. donwa/gclone also shows the same. But tried rclone, that works. Can you fix this please?

**Comment by dogbutcat** [comment]
Could you please provide more detail command example with problem in rclone and gclone, like `gclone copy [drive1]:/[folder] [drive2]:/[folder] -vv`? Also I can't catch what's your system.

From the detail you provide, it looks more like fail to query the ip of `oauth2.googleapis.com`, that means connection failure with google server, network problem instead binary one.

**Comment by l3v11** [comment]
https://github.com/termux/termux-app/issues/1138

Found the same issue here, can you check please?

I'm using Termux on Android..

**Comment by dogbutcat** [comment]
Could you please tell me which rclone version you use can use normally?

I tried rclone on Termux also got same connection error.

**Comment by z8512** [comment]
@dogbutcat https://stackoverflow.com/questions/38959067/dns-lookup-issue-when-running-my-go-app-in-termux
