### ISSUE TITLE
add --drive-service-account-file-path

### ISSUE THREAD

**Issue by 88lex** [dogbutcat/gclone#5]
Thanks for this great update to donwa's gclone. 

`service_account_file_path` in rclone.conf works well, thank you. If you update the fork in the future and if not too much trouble would be handy to also be able to use the command flag `--drive-service-account-file-path` .

Kind regards

**Comment by dogbutcat** [comment]
Thank you for paying attention on this project.

I've received your request, and I need time to dive in the rclone project. But, I can't promise that as having some trouble with my current job.

Thank you for understanding!

**Comment by dogbutcat** [comment]
UPDATE:

release [v1.57.0-mod1.4.0](https://github.com/dogbutcat/gclone/releases/tag/v1.57.0-mod1.4.0) support `--drive-service-account-file-path`

feel free to have a try, I've tested with `copy` without problem in cmd `gclone copy temp:{SOME_ID} temp:{SOME_ID2} --drive-service-account-file-path=/Users/main/accounts/ --drive-server-side-across-configs -v`

**Comment by 88lex** [comment]
> UPDATE:
> 
> release [v1.57.0-mod1.4.0](https://github.com/dogbutcat/gclone/releases/tag/v1.57.0-mod1.4.0) support `--drive-service-account-file-path`
> 
> feel free to have a try, I've tested with `copy` without problem in cmd `gclone copy temp:{SOME_ID} temp:{SOME_ID2} --drive-service-account-file-path=/Users/main/accounts/ --drive-server-side-across-configs -v`

Tested briefly with copy and move. Works. Many thanks!

**Comment by dogbutcat** [comment]
OK, please enjoy it.

If meeting some bug with it, feel free to reopen it. I'll check it if I got.
