### ISSUE TITLE
Not bypassing 750G upload limit

### ISSUE THREAD

**Issue by Christian-Martinez1** [dogbutcat/gclone#6]
Hello, I am trying to use your version of gclone so that I can copy 37TB from one team drive to another. I have set this up with 1000 service accounts and gclone keeps switching service accounts as seen below without copying files:

![image](https://user-images.githubusercontent.com/43798323/149028503-05764b14-23f9-4ff0-a1c7-0c22d7e46f42.png)

I have 10 separate projects each with 100 SA's so that should be plenty of quota to server-side copy all 37TB, but gclone keeps changing service accounts without copying. While typing this up it now looks like this:

![image](https://user-images.githubusercontent.com/43798323/149028635-822a4788-2833-4381-b59b-90841a487f03.png)

How can I fix this? Thanks for your help in advance.

**Comment by dogbutcat** [comment]
I don't know how you set the config, but try use full path name instead relative one, like `/root/accounts/`.

Backend's work is change service
https://github.com/dogbutcat/gclone/blob/b6bc5d0b34c44035cfba8a439e0c97ddcd68b578/backend/drive/drive.go#L743-L748
and change service credential
https://github.com/dogbutcat/gclone/blob/b6bc5d0b34c44035cfba8a439e0c97ddcd68b578/backend/drive/drive.go#L755-L757

**Comment by Christian-Martinez1** [comment]
What are you using to make the service accounts, maybe I made them incorrectly, and what permissions do your SAs have, content manager?

i will try to mirror your setup to make this work so I'll try on ubuntu instead of windows.

**Comment by dogbutcat** [comment]
> Here is my rclone.conf file:
> 
> ```
> [gc]
> type = drive  
> scope = drive  
> service_account_file = /home/user1/sa/1.json  
> service_account_file_path = /home/user1/sa/  
> root_folder_id = 
> ```
> 
> And I am using `gclone copy gc:{teamdrive1idHere} gc:{teamdrive2idHere} --drive-server-side-across-configs --config /home/user1/rclone.conf`
> 
> Just tried with another fresh 100 service accounts but still same issue. :\

Yeah. My config is like these without problem.

I think there is no difference in creating sa account, but exactly the files maybe. Could you check the two folder and  share the file link which failed the copy temporary? 
I don't know if the file meet the requirement of follow 2 conditions:

> Google Shared Drive quota (~20TB/drive/day)
> Google file owner quota (~2TB/day)

**Comment by dogbutcat** [comment]
Temporary close issue.

If you have some new detailed information, please open it again :)
