### ISSUE TITLE
获取到的OneDriveForBusiness的token似乎不正确

### ISSUE THREAD

**Issue by SKIYET** [dogbutcat/gclone#7]
gclone版本是最新的版本

`2022/01/15 22:01:32 NOTICE: Make sure your Redirect URL is set to "http://localhost:53682/" in your custom config.
2022/01/15 22:01:32 NOTICE: If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth?state=NW4ny9eFJ_2wMPo5MeKFxw
2022/01/15 22:01:32 NOTICE: Log in and authorize rclone for access
2022/01/15 22:01:32 NOTICE: Waiting for code...
2022/01/15 22:01:35 NOTICE: Got code
Paste the following into your remote machine --->
eyJ0b2tlbiI6IntcImFjY2Vzc190b2tlblwiOlwiZXlKMGVYQWlPaUpLVjFRaUxDSnViMjVqWlNJNklsWnFVM0ZuWjNWTFYxUk9hVUZuZGtoNlIzbE5NMnh4WjFoNFlUVnRlWHBqV0dseFZtdERUelJHVUhNaUxDSmhiR2NpT2lKU1V6STFOaUlzSW5nMWRDSTZJazF5TlMxQlZXbGlaa0pwYVRkT1pERnFRbVZpWVhoaWIxaFhNQ0lzSW10cFpDSTZJazF5TlMxQlZXbGlaa0pwYVRkT1pERnFRbVZpWVhoaWIxaFhNQ0o5LmV5SmhkV1FpT2lJd01EQXdNREF3TXkwd01EQXdMVEF3TURBdFl6QXdNQzB3TURBd01EQXdNREF3TURBaUxDSnBjM01pT2lKb2RIUndjem92TDNOMGN5NTNhVzVrYjNkekxtNWxkQzlsTlRjMk1USmlOaTFoT0RBMUxUUmtaVGd0WVRJeE15MHdaVGt5TVRkaVkyWXhPVGN2SWl3aWFXRjBJam94TmpReU1qVTBPVGsxTENKdVltWWlPakUyTkRJeU5UUTVPVFVzSW1WNGNDSTZNVFkwTWpJMU9UazVOU3dpWVdOamRDSTZNQ3dpWVdOeUlqb2lNU0lzSW1GcGJ5STZJa1V5V21kWlJFTXJLM1ZyYkZnclRUQklNbUkzWmtVMmRESXpjUzk2Tldrek1TOTFXR05EYUdZelpuVm5iM1ZvZEV4RU9FRWlMQ0poYlhJaU9sc2ljSGRrSWwwc0ltRndjRjlrYVhOd2JHRjVibUZ0WlNJNklrOXVaVVJ5YVhabElFRndjQ0JHYjNJZ1VtTnNiMjVsSWl3aVlYQndhV1FpT2lJNE5qZzFORFkyTnkWTFZemhtWldFMExXTTNOMll0TkdNM01TMWlaRFU1TFRBMVpqVTNZMkk0Wm1RMllpSXNJbkJzWVhSbUlqb2lNeUlzSW5CMWFXUWlPaUl4TURBek1qQXdNVU5FT0VSRk9FUTNJaXdpY21naU9pSXdMa0ZSZDBGMGFFb3lOVkZYYnpaRk1tbEZkelpUUmpkNmVHd3laRWRvV1ZwS1UyeHNSVzVXUjJjME9USXdMV1Z6VFVGQ1FTNGlMQ0p6WTNBaU9pSkdhV3hsY3k1U1pXRmtJRVpwYkdWekxsSmxZV1F1UVd4c0lFWnBiR1Z6TGxKbFlXUlhjbWwwWlNCR2FXeGxjeTVTWldGa1YzSnBkR1V1UVd4c0lGTnBkR1Z6TGxKbFlXUXVRV3hzSUhCeWIyWnBiR1VnYjNCbGJtbGtJR1Z0WVdsc0lpd2ljM1ZpSWpvaWQxWk1jVGhtTUU0eU9FUmZlRmd4VFZKQ2RISk9OMVIwZDB4clVubEVlbEJxUTJWQ1gxRjVSVzV1YnlJc0luUmxibUZ1ZEY5eVpXZHBiMjVmYzJOdmNHVWlPaUpCUmlJc0luUnBaQ0k2SW1VMU56WXhNbUkyTFdFNE1EVXROR1JsT0MxaE1qRXpMVEJsT1RJeE4ySmpaakU1TnlJc0luVnVhWEYxWlY5dVlXMWxJam9pYVVCcGJtSnZlQzR6TURNMk1EWXVlSGw2SWl3aWRYQnVJam9pYVVCcGJtSnZlQzR6TURNMk1EWXVlSGw2SWl3aWRYUnBJam9pU1ZCMFkycHpkV0ZtTUdscWNuRXdSVTlsU1VsQlFTSXNJblpsY2lJNklqRXVNQ0lzSW5kcFpITWlPbHNpWWpjNVptSm1OR1F0TTJWbU9TMDBOamc1TFRneE5ETXROelppTVRrMFpUZzFOVEE1SWwwc0luaHRjMTl6ZENJNmV5SnpkV0lpT2lKVlVWRjFNakZoTm5OUVkyUlhaVFJXVEcxb1JIUTRaVlZUZDA5aWQzbHlUM05UTmtJNFgxUlFSMWxWSW4wc0luaHRjMTkwWTJSMElqb3hOak15TlRjd05EazJmUS5NYUhsWFZNTnU4VDAxdkxVQm5KcnpRb2x1S1R0WE9pY3cycHNKb1ZzX0l1TWFXaWFOS3hiRnNEMTFvXzQzM2g3TTF1ZWxpQlFpOEFOXzRZZjdUZ1c1ZHZpQ3pJX3pTNkp5M0JwM1hub2prdEhkUDg1RHhBUkJaaUpuWTkxSmdCck5CSDBLWmZnSVFZQ1lhYWFqeVE2V1g0UzlCbVlrLXV6SFB5MWYybzh3dnMzU1JQS2lNSjhsbEx4bWtPNllnMGhiUDVwdjN5OGwzYjIteGJmUnY2bFpUMXRFYmxpTUp1ektxN3dvaXZwQUhiSmtrWjBWZ0J6STdJNlZGRHBnTGktUkViaDUxNXd4VlljNGZqX0g3N3J6RVE4Nk5jcl9yWHBsTXBHcXQ0dENDUmNTNk4zdVVSQmpJc3E3Q0hsM3RVYklrYnFBbmROZ0xPaHpJZk5rRlVmaVFcIixcInRva2VuX3R5cGVcIjpcIkJlYXJlclwiLFwicmVmcmVzaF90b2tlblwiOlwiMC5BUXdBdGhKMjVRV282RTJpRXc2U0Y3enhsMmRHaFlaSlNsbEVuVkdnNDkyMC1lc01BQkEuQWdBQkFBQUFBQUQtLURMQTNWTzdRcmRkZ0pnN1dldnJBZ0RzX3dRQTlQOUVmcG9jV3Bzcl9Pb0lOYWFxbzYzbXFHaDJxRTFtVWdqWnNrR0xIaVBQYnFSQ29FTG9rd1VNVHdzcTQ5TDFBZy1feUpaclJtYTJzTzRXaFBibGpjVk14aEpmOFhmUEVIeUxSRjlnS0FMYTc0QXBsZzAwZG43UFN3RFZsY0VCN0hTZjBaSno0NXRLUl90a2dyMWFBdFY2WGtaWjlpdG1sMnMwRHFOSXBiOWEtREhXVVctVlNlY002MThvMHhtdFhZbFV0ZWZVMTBNQm41bGVMN25vdllKVl9HanBlckt2QU9pWmxnb283TS1ZM1I0ZG5iZExkZXNGd0NJQWNid19JTE45aXYwam1sdHhqRGpHa2M0dHVxZjZvelVYaXVZVWRlbnE4b1plSzBCeXgwOFJhQzBCZVRlM1R1dlFIb01KbG9YMXgzQ3ZxcV9mdUgwZC0xNXFlWjI1cWFMXzFkZXpyazdkdS1HcWdFVm5HQlBMWE4wblUxQ1djVmE3X2FpQUszUkdjNFkxcUUzWEdZcU12VUljYzZldjZjWDFrNU5TLW1kdDhQLU1qQko3WGRJZUlVMDlSWDM4SXpTVU5LVmFGbFpTdUJfY1NBQ0RpTEU1b05nN2x3TXlhRHk1X2lDWFRidUdiUTctUjhyVHYyVS1rTjNnSHRoekdiOWtwSThMdGhKQW16RFdiYXlQelJqenZ0WmJzVjA4TS10YWkxLWRaN2VySDVXMnlqc2ZrTGJNdzVtQ21uQ1owdE05WndyQ1dWNnE5aXRwTnFJc3N1bWpZTkd1UkdacDJpTUFQd0hja1FzODdyb245ZXFDcG1wSnMtN1pNQ0ZxYy1URE5pSDA1QzRBaTduZzlEVlNoLXc1dWlGdlhDUFhOZFpUYmxCYmR4RXI4QVllTHVUd1ZiNzVmS1NiRW5JYWEwRFVoRzU3Zk1fTHNvTGl4ZGpJQ1ZnZk9XU2hBVlpOZXRUZVpiOEFoOWJCRlZjT2JIQ29Kclg0dkhyS3VjN0Z4Nmk5aHZPS2lMR0FjbVF5bmlobmo3TUxYdS1hTl9oV0ZCQzYyeGR1RWFmNklRVE9qcDhGanFWdGdwdkRRVzQ2aFh1amRhdERXel9fYnNLT3E0cTY0bVdEYVZ3NnYzQVRfdXBSa1ZrcG1fUzRISk9tMlJGMU51Wjlvb2hEank4SVlfbnE4aGxSZ0IydlBlaHg5ODRcIixcImV4cGlyeVwiOlwiMjAyMi0wMS0xNVQyMzoxOTo1NS4yOTU4MTg5KzA4OjAwXCJ9In0
<---End paste`

这样的很明显不符合Onedrive的token形式，而在服务器上的复制粘贴这样的token也会直接报错。

**Comment by dogbutcat** [comment]
gclone 未改动onedrive的代码

您有尝试过使用原版rclone 是否有同样的问题呢？
