### ISSUE TITLE
gclone speed

### ISSUE THREAD

**Issue by OgnistyPoland** [dogbutcat/gclone#8]
Hello, after adding "--drive-random-pick-sa --drive-rolling-sa --drive-rolling-count=1" at the end of my command. It seems to upload only 1 file instead of 3 "--transfers 3" resulting in lower speeds. Is it possible to fix it, or maybe I did something wrong?

**Comment by fidodone** [comment]
use "--drive-rolling-count=4" to transfers 4 files in parallel

**Comment by dogbutcat** [comment]
@OgnistyPoland please referer comment above, his right.
